HW3 Minghao Chi

1, Read the code below and rewrite it using only numpy functions (without for loop, if-else statements). Benchmark your implementation. How much is it faster than the naive python implementation? (hint: use np.isin)

In [1]:
def func1(names, db):
    idx = []
    for i in names:
        if i in db:
            idx.append(db.index(i))
    return idx

In [2]:
#numpy
import numpy as np
def func1_np(names, db):
    a = np.arange(len(db))
    mask = np.isin(db, names)
    return a[mask]

In [3]:
names = range(5)
db = range(3, 10)
print(func1(names, db))
print(func1_np(names, db))

[0, 1]
[0 1]


In [4]:
names = range(10000)
db = range(5000,15000)
%timeit func1(names, db)

2.12 ms ± 79.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [5]:
%timeit func1_np(names, db)

3.49 ms ± 832 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


2, Use only numpy functions (without for loop, if-else statements) to find the largest 3 distances between points if either points is inside the circle of raidus r0. Then return these points. E.g.

In [8]:
def search_pairs(coordinates, cirle_r0):
    pts_in_r0 = np.linalg.norm(coordinates, axis=1) < cirle_r0 #whether the point is in the circle
    pair_dists = np.linalg.norm(coordinates[:, np.newaxis, :] - coordinates, axis=2) #distance between pair of points
    
    print(pair_dists)
    pair_dists = np.tril(pair_dists, k = -1) #use tril so that you do not repeatly get the result
    print(pair_dists)
    mask = pts_in_r0[: , np.newaxis] ^ pts_in_r0
    mask = np.tril(mask, k=-1) 
    uniq_dists = pair_dists[mask]
    three_largest = np.partition(uniq_dists, -3)[-3:] #choose the first 3 distance, the shortest one
    
    index = np.where(np.isin(pair_dists, three_largest))
    return np.transpose(index)

In [9]:
coordinates = np.array(
[[0.968, 0.313],
 [0.692, 0.876],
 [0.895, 0.085],
 [0.039, 0.17 ],
 [0.878, 0.098]]
)
cirle_r0 = 0.9
print(search_pairs(coordinates, cirle_r0))

[[0.         0.62701276 0.23940134 0.93994149 0.23307724]
 [0.62701276 0.         0.81663333 0.96168862 0.799925  ]
 [0.23940134 0.81663333 0.         0.86020986 0.02140093]
 [0.93994149 0.96168862 0.86020986 0.         0.84208373]
 [0.23307724 0.799925   0.02140093 0.84208373 0.        ]]
[[0.         0.         0.         0.         0.        ]
 [0.62701276 0.         0.         0.         0.        ]
 [0.23940134 0.81663333 0.         0.         0.        ]
 [0.93994149 0.96168862 0.86020986 0.         0.        ]
 [0.23307724 0.799925   0.02140093 0.84208373 0.        ]]
[[2 1]
 [3 0]
 [3 1]]
